"""empty message

Revision ID: 6cbe1e9680b5
Revises: eb322b88213c
Create Date: 2020-11-23 13:53:16.108588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbe1e9680b5'
down_revision = 'eb322b88213c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reader', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Enum('1', '2', '3', '4', '5'), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_reader'], ['reader.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_reader', 'id_book')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
