"""empty message

Revision ID: 92ed4fa15d50
Revises: 6cbe1e9680b5
Create Date: 2020-11-23 13:59:49.399781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ed4fa15d50'
down_revision = '6cbe1e9680b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf',
    sa.Column('id_reader', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('shelf_name', sa.Enum('Comentados', 'Leídos', 'Favoritos', 'Pendientes', 'Comprados'), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_reader'], ['reader.id'], ),
    sa.PrimaryKeyConstraint('id_reader', 'id_book')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf')
    # ### end Alembic commands ###
