"""empty message

Revision ID: eb322b88213c
Revises: 8b6cca2ba9a5
Create Date: 2020-11-23 13:49:30.849001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb322b88213c'
down_revision = '8b6cca2ba9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id_follower', sa.Integer(), nullable=True),
    sa.Column('id_followed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_followed'], ['reader.id'], ),
    sa.ForeignKeyConstraint(['id_follower'], ['reader.id'], )
    )
    op.create_table('written_by',
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], )
    )
    op.create_table('order_line',
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_order'], ['order.id'], )
    )
    op.add_column('order', sa.Column('reader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'reader', ['reader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'reader_id')
    op.drop_table('order_line')
    op.drop_table('written_by')
    op.drop_table('follower')
    # ### end Alembic commands ###
